import React, {useContext} from "react";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {StaticLayout} from "@/app/StaticLayout";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="uk-UA">
            <body>
                <StaticLayout>
                    {children}
                </StaticLayout>
            </body>
        </html>
    );
}
